# Generated by Django 4.0.2 on 2022-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hometitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometitle',
            options={'verbose_name': 'Home Title', 'verbose_name_plural': 'Home Title'},
        ),
        migrations.RenameField(
            model_name='hometitle',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='hometitle',
            name='title2',
            field=models.TextField(default='work', max_length=100),
            preserve_default=False,
        ),
    ]
