# Generated by Django 4.0.2 on 2022-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContactsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FooterMenusMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterServicesMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='footerlogometa',
            options={'verbose_name': 'Logo Meta', 'verbose_name_plural': 'Logo Meta'},
        ),
        migrations.AlterField(
            model_name='footerlogometa',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='footerlogometa',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='footerlogometa',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='footerlogometa',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
